### ISSUE TITLE
True OrElse getting rendered as just '1'

### ISSUE THREAD

**Issue by scott-mac** [gambarra/ExpressionExtensionSQL#6]
Not sure if you are familiar with the PredicateBuilder but it is quite popular and allows easy building on the fly. I've been using [this particular version](https://petemontgomery.wordpress.com/2011/02/10/a-universal-predicatebuilder/) of it because it does not rely Linq-to-Sql InvocationExpressions (which definitely won't work with this extension you've built). So for example it allows us to build it with multiple ANDs and ORs in the WHERE clause like this:

```
var inner = PredicateBuilder.False<Product>();
inner = inner.Or(p => p.ProductGroupID == 10);
inner = inner.Or(p => p.ProductGroupID == 11);

var outer = PredicateBuilder.True<Product>();
outer = outer.And(p => p.StatusID == 2);
outer = outer.And(inner);
```

That first line is causing the issue, it's supposed to be just an entry point for the expression tree to build off of but when the SQL gets generated you wind up with (note: bolded sections):

SELECT * FROM [Product]  WHERE (**(1 AND** ([Product].[StatusID] = ( 2))) AND ((**0 OR** ([Product].[ProductGroupID] = ( 10))) OR ([Product].[ProductGroupID] = ( 11))))

Looking at the expression being built by the PredicateBuilder you see

`(True OrElse (param.ProductGroupID == Convert(10, Nullable`1)))`

So that True OrElse is causing the problem, it probably should get rendered as 1=1 instead of just 1? What do you think?

**Comment by gambarra** [comment]
Thanks for the contribution. I'm studying the modifications. Once you get a final solution a new version will be generated.

**Comment by scott-mac** [comment]
I should have mentioned, I get this error with the ExpressionExtensionSQL.Dapper package so it seems to be something with how it is translating the boolean to a bit 1 or 0 for the SQL expression

**Comment by scott-mac** [comment]
Thiago,

I was able to fix this by making the following change to the Concat method:

```
public static WherePart Concat(WherePart left, string @operator, WherePart right) {
            if (right.Sql.Equals("NULL", StringComparison.InvariantCultureIgnoreCase)) {
                @operator = @operator == "=" ? "IS" : "IS NOT";
            }
            if(left.Sql == "1") {
                left.Sql = "(1=1)";
            }
            if (left.Sql == "0") {
                left.Sql = "(0=0)";
            }
            var w = new WherePart() {
                Parameters = left.Parameters.Union(right.Parameters).ToDictionary(kvp => kvp.Key, kvp => kvp.Value),
                Sql = $"({left.Sql} {@operator} {right.Sql})"
            };
            return w;
        }

```

I don't think that's a very good solution but your code is very efficient, nested and recursive so I was not able to figure out the best spot to implement a fix. 

But the issue arises where the left part of the expression starts with "True AndAlso ..." so just a boolean (i.e. 'True') with no property tied to it (i.e. TableName.PropertyName = True) is what gets interpreted so it just extracts a 1 or a 0

**Comment by gambarra** [comment]
Good Morning. I will do the correction today and upload a new version in nuget

**Comment by gambarra** [comment]
Fixed and new package released. Please check.

**Comment by scott-mac** [comment]
That seems to work for me, I'll continue testing it this week, thank you
